on:
  pull_request:
    branches:
      - main
name: PR Workflow
jobs:
  validate_configurations:
    name: Validate versions JSON files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Versions schema
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: release.jsonschema
          json_path_pattern: \d{4}\.\d{1}\.\d+.json$
          send_comment: true
          clear_comments: true
